apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 8080
      protocol: TCP
      name: aqua-web
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.web.nodePort) }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: 8443
      protocol: TCP
      name: aqua-web-ssl
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.grpc.nodePort) }}
      nodePort: {{ .Values.service.grpc.nodePort }}
      {{- end }}
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
