apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ssh.port }}
      targetPort: 3622
      protocol: TCP
      name: aqua-gateway
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.ssh.nodePort) }}
      nodePort: {{ .Values.service.ssh.nodePort }}
      {{- end }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: 8443
      protocol: TCP
      name: aqua-gateway-ssl
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.grpc.nodePort) }}
      nodePort: {{ .Values.service.grpc.nodePort }}
      {{- end }}
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
